# Generated by Django 4.2.1 on 2023-05-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile", options={"get_latest_by": "modified"},
        ),
    ]
