version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3.12.7-management
    ports:
      - "5672:5672"
      # GUI port
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=sensorsafrica
      - RABBITMQ_DEFAULT_PASS=sensorsafrica
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 5s
      retries: 2

  postgres:
    image: postgres:13.7
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=sensorsafrica
      - POSTGRES_PASSWORD=sensorsafrica
      - POSTGRES_DB=sensorsafrica
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build:
      context: .
    environment:
      SENSORSAFRICA_DATABASE_URL: ${SENSORSAFRICA_DATABASE_URL}
      SENSORSAFRICA_RABBITMQ_URL: ${SENSORSAFRICA_RABBITMQ_URL}
      SENSORSAFRICA_FLOWER_ADMIN_USERNAME: ${SENSORSAFRICA_FLOWER_ADMIN_USERNAME}
      SENSORSAFRICA_FLOWER_ADMIN_PASSWORD: ${SENSORSAFRICA_FLOWER_ADMIN_PASSWORD}
      DOKKU_APP_NAME: sensorsafrica
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
    volumes:
      - .:/src
    ports:
      - "8000:8000"
      - "5555:5555"

volumes:
  postgres_data:
