version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
  web:
    build:
      context: .
      dockerfile: ./docker_compose/production/Dockerfile
    command: /start.sh
    container_name: sensors_africa
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/sensors_africa
    ports:
      - "8000:8000"
  nginx:
    container_name: nginx_server
    build: ./docker_compose/nginx
    depends_on:
      - web
    ports:
      - "0.0.0.0:80:80"
