version: '3.3'

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 4369:4369
      - 5672:5672
      - 25672:25672
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=sensorsafrica
      - RABBITMQ_PASSWORD=sensorsafrica
  postgres:
    image: postgres:9.6
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=sensorsafrica
      - POSTGRES_PASSWORD=sensorsafrica
      - POSTGRES_DB=sensorsafrica
  api:
    build:
      context: .
    environment:
      SENSORSAFRICA_DATABASE_URL: postgres://sensorsafrica:sensorsafrica@postgres:5432/sensorsafrica
      DOKKU_APP_NAME: sensorsafrica
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
    volumes:
      - .:/src
    ports:
      - "8000:8000"
