version: '3'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
  web:
    build:
      context: .
      dockerfile: ./docker_compose/development/Dockerfile
    command: /start.sh
    container_name: sensors_africa
    environment:
      DJANGO_SETTINGS_MODULE: sensors_africa.settings.docker
      PYTHONUNBUFFERED: 0
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/sensors_africa
    ports:
      - "8000:8000"