version: '3.3'

services:
  # localstack:
  #     image: localstack/localstack
  #     ports:
  #       - "4567-4599:4567-4599"
  #       - "8080:8080"
  #     environment:
  #       - DEBUG=1
  telegraf:
    image: telegraf
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define an InfluxDB service
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: sensorsafrica
      POSTGRES_PASSWORD: sensorsafrica
      POSTGRES_DB: sensorsafrica
    ports:
      - "5432:5432"
  influxdb:
    image: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: sensorsafrica
      INFLUXDB_ADMIN_USER: sensorsafrica
      INFLUXDB_ADMIN_PASSWORD: sensorsafrica
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
      GF_INSTALL_PLUGINS: grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    # User ID changes
    user: "0"
    links:
      - influxdb
  # Define a Chronograf service
  chronograf:
    image: chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_ADMIN_USER: sensorsafrica
      INFLUXDB_ADMIN_PASSWORD: sensorsafrica
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor
  # Define a Kapacitor service
  kapacitor:
    image: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"
  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
  kapacitor-cli:
    image: kapacitor
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - kapacitor
