version: '3.3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=sensorsafrica
      - POSTGRES_PASSWORD=sensorsafrica
      - POSTGRES_DB=sensorsafrica
  api:
    build:
      context: .
    environment:
      SENSORSAFRICA_DATABASE_URL: postgres://sensorsafrica:sensorsafrica@postgres:5432/sensorsafrica
      DOKKU_APP_NAME: sensorsafrica
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/src
    ports:
      - "8000:8000"
