version: '3.7'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=sensorsafrica
      - POSTGRES_PASSWORD=sensorsafrica
      - POSTGRES_DB=sensorsafrica
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker_compose/development/Dockerfile
    command: /start.sh
    container_name: sensors_africa
    environment:
      PYTHONUNBUFFERED: 0
      #Used in entrypoint
      DATABASE_URL: postgresql://sensorsafrica:sensorsafrica@postgres:5432/sensorsafrica 
      #Used in settings
      DBNAME: sensorsafrica
      DBUSER: sensorsafrica
      DBPASS: sensorsafrica
      DBHOST: postgres
      DBPORT: 5432
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/sensors_africa
    ports:
      - "8000:8000"