# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 19:07
from __future__ import unicode_literals

import django_extensions.db.fields
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    City = apps.get_model("sensorsafrica", "City")
    City.objects.bulk_create(
        [
            City(
                latitude=6.5244,
                longitude=3.3792,
                slug="lagos",
                name="Lagos",
                country="Nigeria",
                map_zoom=12,
            ),
            City(
                latitude=-1.2921,
                longitude=36.8219,
                slug="nairobi",
                name="Nairobi",
                country="Kenya",
                map_zoom=12,
            ),
            City(
                latitude=-6.7924,
                longitude=39.2083,
                slug="dar-es-salaam",
                name="Dar es Salaam",
                country="Tanzania",
                map_zoom=12,
            ),
        ]
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("sensorsafrica", "0001_sensordatastat")]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("slug", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("country", models.CharField(db_index=True, max_length=255)),
                ("location", models.CharField(db_index=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=14, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=14, null=True
                    ),
                ),
                ("map_zoom", models.IntegerField(default=12)),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
