# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        # ('sensors', '0020_auto_20190314_1232'),
        ('sensorsafrica', '0003_auto_20190222_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastActiveNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('last_data_received_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.SensorLocation')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Node')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lastactivenodes',
            unique_together=set([('node', 'location')]),
        ),
    ]
