# Generated by Django 4.2.1 on 2023-05-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensorsafrica", "0004_auto_20190509_1145"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sensordatastat", options={"get_latest_by": "modified"},
        ),
    ]
