# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsafrica', '0004_auto_20190509_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordatastat',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sensordatastat',
            name='node',
        ),
        migrations.RemoveField(
            model_name='sensordatastat',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='SensorDataStat',
        ),
    ]
