# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_sensordatastat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordatastat',
            name='last_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sensordatastat',
            name='sample_size',
            field=models.IntegerField(default=0),
        ),
    ]
